apiVersion: v1
kind: Deployment
metadata:
  name: my-deploy
  namespace: my-ns
spec: 
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-container
          image: nginx
          env:
            - name: APP_DRIVER_URL
              valueFrom:
                configMapKeyRef:
                  name: my-config
                  key: MY_DRIVER_URL
            - name: APP_DATABASE_NAME
              valueFrom:  
                configMapKeyRef:
                  name: my-config
                  key: MY_DATABASE_NAME
            - name: APP_USER
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: username
