apiVersion: v1
kind: Service
metadata:
  name: my-service-app
  labels:
    type: new-app
spec:
  type: NodePort
  ports: 
    - targetPort: 8080
      port: 9090
      nodePort: 30006
  selector:
    app: back-end
    type: web-app
