apiVersion: v1
kind: Pod
metadata:
  name: my-sql-pod
  namespace: my-sql-ns
spec:
  containers:
    - name: my-sql
      image: mysql:latest
      env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef: 
              name: mysql-secret
              key: user-name
        - name: DB_PASSWORDz
          valueFrom:
            secretKeyRef: 
              name: mysql-secret
              key: password
