---
  - name: find Java version
    hosts: all
    become: true
    gather_facts: true
    tasks:
      - name: java version
        shell: java --version
        register: output
      - name: display output
        debug: 
          var: output.stdout
