---
  - name: Install Java
    hosts: all
    become: true
    gather_facts: true
    tasks:
      - name: JavaInstallation
        yum:
          name: java-11-amazon-corretto-1:11.0.18+10-1.amzn2023.x86_64
          state: present
